spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_minapp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

my:
  shiro:
      # 后端免认证接口 url
      anonUrl: /login,/actuator/*,/captcha.jpg
      # token有效期，单位秒
      jwtTimeOut: 3600

server:
  port: 8089
